<?php
function dw_views_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
    // If you want you can add a template suggestion for all views
    // based on their ID:
    $suggestions[] = sprintf('views_view__%s', $variables['view']->id());
    $suggestions[] = sprintf('views_view__%1$s__%2$s', $variables['view']->id(), $variables['view']->current_display);
    // Or you can check the ID, add suggestions, do whatever you want
    // ...
}

function dw_views_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables) {
    // If you want you can add a template suggestion for all views
    // based on their ID:
    $suggestions[] = sprintf('views_view_unformatted__%s', $variables['view']->id());
    $suggestions[] = sprintf('views_view_unformatted__%1$s__%2$s', $variables['view']->id(), $variables['view']->current_display);

    // Or you can check the ID, add suggestions, do whatever you want
    // ...

}

function dw_views_theme_suggestions_views_view_table_alter(array &$suggestions, array $variables) {
    // If you want you can add a template suggestion for all views
    // based on their ID:
    $suggestions[] = sprintf('views_view_table__%s', $variables['view']->id());
    $suggestions[] = sprintf('views_view_table__%1$s__%2$s', $variables['view']->id(), $variables['view']->current_display);

    // Or you can check the ID, add suggestions, do whatever you want
    // ...

}

function dw_views_theme_suggestions_views_view_field_alter(array &$suggestions, array $variables) {
    // If you want you can add a template suggestion for all views
    // based on their ID:
    $suggestions[] = sprintf('views_view_field__%s', $variables['view']->id());
    $suggestions[] = sprintf('views_view_field__%1$s__%2$s', $variables['view']->id(), $variables['view']->current_display);

    $field = $variables['field']->field;
    $suggestions[] = sprintf('views_view_field__%1$s__%2$s', $variables['view']->id(), $field);
    $suggestions[] = sprintf('views_view_field__%1$s__%2$s__%3$s', $variables['view']->id(), $variables['view']->current_display, $field);
}
?>
